  


Resources: 
  APITest:
    Type: AWS::ApiGateway::RestApi
    Properties: 
      BinaryMediaTypes: 
        - RestApi
      Body: OpenAPI
      # BodyS3Location: 
      #   S3Location
      CloneFrom: String
      Description: Just testing for API Gateway
      DisableExecuteApiEndpoint: True
#      EndpointConfiguration: 
      FailOnWarnings: False
      MinimumCompressionSize: 1
      Mode: overwrite
      Name: Name
      Parameters: 
        Key : Name
        Value: APITest
      Policy: Json
      Tags: 
        - Key: name
          Value: Hello
