# test
Parameters:
 InstanceType:
   Description: Reference for the InstanceType
   Type: String
   Default: t3.micro
   AllowedValues: 
     - t3.micro


Mappings:
  AWSRegionAMI:
    ap-southeast-1:
      HVM64: ami-0c802847a7dd848c0
    us-east-1:
      HVM64: ami-0cff7528ff583bf9a
    ap-east-1:
      HVM64: ami-0bf6e149a5267c1af



Resources:
  ASGCF:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ASG_CF
      DesiredCapacity: 1
      DesiredCapacityType: t3.micro
      Cooldown: 10
      CapacityRebalance: false
      
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AWSRegionAMI, !Ref 'AWS::Region', HVM64]
      AvailabilityZone: us-east-1d
      InstanceType: t3.micro
      EbsOptimized: false
      SecurityGroups:
        - !Ref SSHSecurityGroup
        # EBS volume setup
      BlockDeviceMappings:
        - DeviceName: /dev/sdc
          Ebs:
            VolumeSize: 15
            VolumeType: gp3
            DeleteOnTermination: "true"
      Tags:
        - Key: Name
          Value: CFTest
     DependsOn: MyInstance2

        
  MyInstance2:
    Type: AWS::EC2::Instance
    #DeletionPolicy: Retain
    Properties:
      ImageId: !FindInMap [AWSRegionAMI, !Ref 'AWS::Region', HVM64] 
      AvailabilityZone: us-east-1d
      InstanceType: t3.micro
      EbsOptimized: false
      SecurityGroups:
        - !Ref SSHSecurityGroup
      BlockDeviceMappings:
      - DeviceName: /dev/sdc
        Ebs:
          VolumeSize: 15
          VolumeType: gp3
          DeleteOnTermination: "true"
      Tags:
        - Key: Name
          Value: Another instance 


  
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 22
        ToPort: 22
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 3389
        ToPort: 3389
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 443
        ToPort: 443
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        FromPort: 80
        ToPort:   80
   
Outputs:
  SGOutput:
    Description: Output for SG Group sample
    Value: !Ref SSHSecurityGroup
    Export:
      Name: SGoutput
      
  Instanceoutput:
    Description: Output for EC2 instance
    Value: !Ref MyInstance
    Export: 
      Name: InstanceOutput

    
